apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-helloworld
  namespace: talfinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-helloworld
  template:
    metadata:
      labels:
        app: spring-helloworld
    spec:
      containers:
      - name: spring-helloworld
        image: gcr.io/codepro-b61b8/gceme
        imagePullPolicy: Always
        ports:
        - containerPort: 80